version: '3.7'
name: 'ktor-mongodb-mongock'
services:
  mongodb:
      image: mongo:6
      ports:
        - '27017:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: test
